# Example command:
#   Humble on a Nvidia system:
#   DOCKER_IMAGE=humble-tutorial docker compose run gpu
#   Rolling without discrete graphics:
#   DOCKER_IMAGE=rolling-tutorial docker compose run cpu
#   docker compose run --rm gpu
#   docker compose run --name ros2-tf gpu

services:
  cpu:
    # image: ghcr.io/ros-planning/moveit2_tutorials:$DOCKER_IMAGE
    image: ros2-tf:latest
    container_name: ros2-tf
    privileged: true
    network_mode: host
    command: /bin/bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ~/code/ros/docker_moveit2_tutorials_ws_host/:/root/ws_host
    working_dir: /root
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      # all_proxy: socks5://127.0.0.1:7890
  gpu:
    # image: ghcr.io/ros-planning/moveit2_tutorials:$DOCKER_IMAGE
    image: ros2-tf:latest
    container_name: ros2-tf
    privileged: true
    network_mode: host
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ~/code/ros/docker_moveit2_tutorials_ws_host/:/root/ws_host
    working_dir: /root
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      # all_proxy: socks5://127.0.0.1:7890
